name: Lint Validations

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:
  pr-title-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Secrets
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BW_PIPELINE_ACCESS_TOKEN }}
          secrets: |
            73fd78b1-23c6-446a-afdd-b16400945670 > GITHUB_TOKEN

      - uses: thehanimo/pr-title-checker@v1.4.2
        with:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
          pass_on_octokit_error: false
          remote_configuration_url: "https://raw.githubusercontent.com/deweb-services/.github/main/config/pr_title_checker_config.json"

  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v6
