# ------ need to fill <service name> value
name: Release <service name>

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch Secrets
        uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BW_PIPELINE_ACCESS_TOKEN }}
          # ------ need to fill <bw_id> values
          secrets: |
            <bw_id> > REGISTRY_USER
            <bw_id> > REGISTRY_PASSWORD

      - name: Login to remote registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # ------ need to fill <service name> value
          images: |
            ghcr.io/${{ github.repository }}/<service name>
          tags: |
            type=schedule
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          # ------ need to fill <service name> value
          tags: |
            ghcr.io/${{ github.repository }}/<service name>:latest
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          context: .
